name: Auto-merge bot PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'pre-commit-ci[bot]') &&
      github.repository == 'sgibson91/bump-helm-deps-action'
    steps:
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
